apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/punithbrave/go-microservice.git
    targetRevision: HEAD
    path: k8s  # Assuming your Kubernetes manifests are in a k8s directory
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true