# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: go-microservice
spec:
  type: NodePort
  selector:
    app: go-microservice
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080